import React from "react";

// Minimal CORE-8 dashboard page: list + quick create + accept/reject.
// This is intentionally simple and uses fetch() directly to match existing patterns.

type ProposalDraft = {
  id: number;
  source_text: string;
  draft_payload: any;
  status: string;
  created_at: string;
};

async function apiFetch(path: string, init?: RequestInit) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}${path}`, {
    cache: "no-store",
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`${res.status} ${res.statusText}: ${text}`);
  }
  return res.json();
}

export default async function ProposalsPage() {
  const drafts: ProposalDraft[] = await apiFetch("/api/objectives/proposal-drafts");

  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 24, fontWeight: 700 }}>Goals / Proposals</h1>
      <p style={{ opacity: 0.8, marginTop: 8 }}>
        Review goal proposals generated by the autopilot. (CORE-8 minimal UI)
      </p>

      <div style={{ marginTop: 24, display: "grid", gap: 12 }}>
        {drafts.length === 0 ? (
          <div style={{ padding: 16, border: "1px solid #333", borderRadius: 12 }}>
            No proposal drafts yet.
          </div>
        ) : (
          drafts.map((d) => (
            <div
              key={d.id}
              style={{ padding: 16, border: "1px solid #333", borderRadius: 12 }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
                <div>
                  <div style={{ fontWeight: 700 }}>Draft #{d.id}</div>
                  <div style={{ fontSize: 12, opacity: 0.7 }}>
                    {d.status} · {new Date(d.created_at).toLocaleString()}
                  </div>
                </div>
              </div>
              <pre
                style={{
                  marginTop: 12,
                  padding: 12,
                  background: "#111",
                  borderRadius: 8,
                  overflow: "auto",
                  maxHeight: 240,
                }}
              >
                {d.source_text}
              </pre>

              {/*
                NOTE: Server actions / client components would be nicer, but this is a minimal skeleton.
                Buttons below are placeholders for wiring in a follow-up.
              */}
              <div style={{ marginTop: 12, display: "flex", gap: 8 }}>
                <form
                  action={async () => {
                    "use server";
                    await apiFetch(`/api/objectives/proposal-drafts/${d.id}/review`, {
                      method: "POST",
                      body: JSON.stringify({ action: "accept" }),
                    });
                  }}
                >
                  <button type="submit">Accept</button>
                </form>
                <form
                  action={async () => {
                    "use server";
                    await apiFetch(`/api/objectives/proposal-drafts/${d.id}/review`, {
                      method: "POST",
                      body: JSON.stringify({ action: "reject" }),
                    });
                  }}
                >
                  <button type="submit">Reject</button>
                </form>
              </div>
            </div>
          ))
        )}
      </div>

      <div style={{ marginTop: 32, padding: 16, border: "1px solid #333", borderRadius: 12 }}>
        <h2 style={{ fontSize: 18, fontWeight: 700 }}>Create (manual)</h2>
        <p style={{ opacity: 0.7, marginTop: 6 }}>
          Minimal create form. Paste source text to create a draft.
        </p>
        <form
          action={async (formData) => {
            "use server";
            const source_text = String(formData.get("source_text") || "");
            await apiFetch("/api/objectives/proposal-drafts", {
              method: "POST",
              body: JSON.stringify({ source_text }),
            });
          }}
        >
          <textarea
            name="source_text"
            placeholder="Describe your goal idea…"
            style={{ width: "100%", minHeight: 120, marginTop: 10 }}
          />
          <div style={{ marginTop: 10 }}>
            <button type="submit">Create draft</button>
          </div>
        </form>
      </div>
    </div>
  );
}
